<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<section class="container mt-5">
    <nav>
        <a href="listar.php" class="btn btn-outline-dark">Listar</a>
        <a href="adicionar.php" class="btn btn-outline-dark">Novo</a>
    </nav>

    <hr>

    <div class="card card-body">
        <table class="table table-striped table-hover">
            <thead class="table-dark">
                <tr>
                    <th>#ID</th>
                    <th>Nome</th>
                    <th>Quantidade</th>
                    <th>Ações</th>
                </tr>
            </thead>
            <tbody>
                <?php
                    foreach ($bebidas as $bebida) {
                        echo "<tr>
                            <td>{$bebida['id']}</td>
                            <td>{$bebida['nome']}</td>
                            <td>{$bebida['quantidade']}</td>
                            <td>
                                <a href='#' class='btn btn-outline-warning btn-sm'>Editar</a>
                                <a href='#' class='btn btn-outline-danger btn-sm'>Excluir</a>
                            </td>
                        </tr>";
                    }
                ?>
            </tbody>
        </table>
    </div>
</section>