<!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

<section class="container mt-5">
    <nav>
        <a href="listar.php" class="btn btn-outline-dark">Listar</a>
        <a href="adicionar.php" class="btn btn-outline-dark">Novo</a>
    </nav>

    <hr>

    <div class="row align-items-center">
        <div class="col">
            <img src="../img/beer.svg" width="80%" alt="">
        </div>
        <div class="col">
            <div class="card card-body">
                <form action="" method="post">
                    <label for="nome">Nome</label>
                    <input type="text" id="nome" name="nome" class="form-control mb-3">

                    <label for="quantidade">Quantidade</label>
                    <input type="text" id="quantidade" name="quantidade" class="form-control mb-3">

                    <div class="d-grid">
                        <button class="btn btn-success">Pronto</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>